Be sure we don't pass invalid parameters
Don't pass too high a DatapointsToAlarm when a lower evaluation period is used.

To avoid:
```
ValidationError: DatapointsToAlarm must be less than or equal to EvaluationPeriods
```